export const COMPLETION_SHELLS = ["bash", "zsh", "fish", "powershell", "nushell"] as const;

export type CompletionShell = (typeof COMPLETION_SHELLS)[number];

interface CompletionCommand {
  name: string;
  description: string;
  values?: readonly string[];
}

const COMMANDS: readonly CompletionCommand[] = [
  { name: "agent", description: "Configure a project-local AI agent bridge", values: ["setup"] },
  {
    name: "app",
    description: "Resolve, inspect, install, or control one app",
    values: ["resolve", "info", "install", "launch", "stop", "restart", "clear-data", "uninstall"],
  },
  { name: "apps", description: "List packages on one Android target", values: ["list"] },
  {
    name: "capture",
    description: "Capture verified device evidence",
    values: ["screenshot", "screen-record"],
  },
  { name: "completion", description: "Generate shell completion", values: COMPLETION_SHELLS },
  {
    name: "config",
    description: "Validate or explain configuration",
    values: ["validate", "explain"],
  },
  { name: "connect", description: "Connect a wireless Android target" },
  { name: "context", description: "Export bounded AI-ready context" },
  { name: "dev", description: "Start a target-bound development session" },
  { name: "devices", description: "List visible Android targets" },
  { name: "doctor", description: "Inspect the local ADB environment" },
  { name: "help", description: "Show command help" },
  { name: "init", description: "Create detected project configuration" },
  {
    name: "inspect",
    description: "Build bounded device evidence",
    values: ["app", "failures", "ui"],
  },
  { name: "logs", description: "Stream focused target logs" },
  { name: "mcp", description: "Serve typed tools over local stdio" },
  { name: "open", description: "Open a deep link or web URL" },
  { name: "pair", description: "Pair through Wireless debugging" },
  { name: "ports", description: "Manage verified TCP mappings", values: ["forward", "reverse"] },
  { name: "problems", description: "Show saved session problems" },
  { name: "run", description: "Run one bounded verification job" },
  { name: "sessions", description: "Inspect saved sessions", values: ["list", "show", "events"] },
  { name: "test", description: "Run managed Android tests", values: ["gradle", "firebase"] },
  {
    name: "ui",
    description: "Perform a bounded verified UI action",
    values: [
      "audit",
      "find",
      "get",
      "assert",
      "compare",
      "tap",
      "long-press",
      "scroll",
      "swipe",
      "fill",
      "clear",
      "type",
      "press",
      "keyboard",
      "permission",
      "wait",
    ],
  },
  { name: "version", description: "Show version" },
];

const GLOBAL_OPTIONS = [
  "--help",
  "-h",
  "--version",
  "-V",
  "--format",
  "--json",
  "--quiet",
  "--verbose",
  "--color",
  "--no-color",
  "--unicode",
  "--no-unicode",
  "--animation",
  "--no-animation",
  "--non-interactive",
  "--timeout",
  "--adb",
  "--adb-host",
  "--adb-port",
  "--config",
  "--profile",
  "--select",
  "--device",
  "--serial",
  "-s",
  "--transport-id",
  "--last",
  "--dry-run",
] as const;

const commandNames = (): string => COMMANDS.map(({ name }) => name).join(" ");
const optionNames = (): string => GLOBAL_OPTIONS.join(" ");

function bash(): string {
  const cases = COMMANDS.filter(({ values }) => values !== undefined)
    .map(({ name, values }) => `      ${name}) candidates="${values?.join(" ")}" ;;`)
    .join("\n");
  return `# Generated by adb-ready. Source this file from ~/.bashrc.
_adb_ready_complete() {
  local current command candidates
  COMPREPLY=()
  current="\${COMP_WORDS[COMP_CWORD]}"
  command="\${COMP_WORDS[1]}"
  if [[ \${COMP_CWORD} -eq 1 ]]; then
    candidates="${commandNames()} ${optionNames()}"
  elif [[ \${COMP_CWORD} -eq 2 ]]; then
    case "\${command}" in
${cases}
      help) candidates="${commandNames()}" ;;
      *) candidates="${optionNames()}" ;;
    esac
  else
    candidates="${optionNames()}"
  fi
  COMPREPLY=( $(compgen -W "\${candidates}" -- "\${current}") )
}
complete -F _adb_ready_complete adb-ready adbr
`;
}

function zsh(): string {
  const commands = COMMANDS.map(
    ({ name, description }) => `    '${name}:${description.replaceAll("'", "'\\''")}'`,
  ).join("\n");
  const cases = COMMANDS.filter(({ values }) => values !== undefined)
    .map(({ name, values }) => `      ${name}) _values 'action' ${values?.join(" ")} ;;`)
    .join("\n");
  return `#compdef adb-ready adbr
# Generated by adb-ready. Add its directory to fpath, then run compinit.
_adb_ready() {
  local -a commands
  commands=(
${commands}
  )
  _arguments -C \\
    '(-h --help)'{-h,--help}'[show help]' \\
    '(-V --version)'{-V,--version}'[show version]' \\
    '--format[select output format]:format:(human plain json ndjson)' \\
    '--json[emit JSON]' \\
    '--non-interactive[never prompt]' \\
    '1:command:->command' \\
    '*::argument:->argument'
  case $state in
    command) _describe 'command' commands ;;
    argument)
      case $words[2] in
${cases}
        help) _describe 'command' commands ;;
      esac
      ;;
  esac
}
_adb_ready "$@"
`;
}

function fish(): string {
  const lines: string[] = [
    "# Generated by adb-ready. Save as ~/.config/fish/completions/adb-ready.fish.",
  ];
  for (const binary of ["adb-ready", "adbr"]) {
    for (const { name, description } of COMMANDS) {
      const safeDescription = description.replaceAll("'", "\\'");
      lines.push(
        `complete -c ${binary} -f -n '__fish_use_subcommand' -a '${name}' -d '${safeDescription}'`,
      );
    }
    for (const { name, values } of COMMANDS) {
      if (values === undefined) continue;
      lines.push(
        `complete -c ${binary} -f -n '__fish_seen_subcommand_from ${name}' -a '${values.join(" ")}'`,
      );
    }
    lines.push(
      `complete -c ${binary} -s h -l help -d 'Show help'`,
      `complete -c ${binary} -s V -l version -d 'Show version'`,
      `complete -c ${binary} -l json -d 'Emit JSON'`,
      `complete -c ${binary} -l non-interactive -d 'Never prompt'`,
      `complete -c ${binary} -l dry-run -d 'Plan without mutation'`,
    );
  }
  return `${lines.join("\n")}\n`;
}

function powershell(): string {
  const map = COMMANDS.filter(({ values }) => values !== undefined)
    .map(({ name, values }) => `  '${name}' = @('${values?.join("','")}')`)
    .join("\n");
  return `# Generated by adb-ready. Add this script to your PowerShell profile.
$AdbReadyCommands = @('${commandNames().replaceAll(" ", "','")}')
$AdbReadyOptions = @('${optionNames().replaceAll(" ", "','")}')
$AdbReadyActions = @{
${map}
}
Register-ArgumentCompleter -Native -CommandName adb-ready,adbr -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $words = $commandAst.CommandElements | ForEach-Object { $_.Extent.Text }
  $candidates = if ($words.Count -le 1) {
    $AdbReadyCommands + $AdbReadyOptions
  } elseif ($words.Count -eq 2 -and $AdbReadyActions.ContainsKey($words[1])) {
    $AdbReadyActions[$words[1]] + $AdbReadyOptions
  } elseif ($words[1] -eq 'help') {
    $AdbReadyCommands
  } else {
    $AdbReadyOptions
  }
  $candidates | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
  }
}
`;
}

function nushellExtern(binary: string): string {
  return `export extern "${binary}" [
  command?: string@"nu-complete adb-ready commands"
  ...args: string
  --help(-h)
  --version(-V)
  --json
  --quiet
  --verbose
  --non-interactive
  --dry-run
]`;
}

function nushell(): string {
  const records = COMMANDS.map(
    ({ name, description }) => `  { value: "${name}", description: "${description}" }`,
  ).join("\n");
  return `# Generated by adb-ready. Source this file from config.nu.
def "nu-complete adb-ready commands" [] {
[
${records}
]
}

${nushellExtern("adb-ready")}

${nushellExtern("adbr")}
`;
}

export function generateCompletion(shell: CompletionShell): string {
  switch (shell) {
    case "bash":
      return bash();
    case "zsh":
      return zsh();
    case "fish":
      return fish();
    case "powershell":
      return powershell();
    case "nushell":
      return nushell();
  }
}
