import { describe, expect, test } from "bun:test";
import {
  renderAgentSkill,
  stringifyAgentContract,
} from "../../scripts/lib/generate-agent-contract.mjs";

describe("agent contract generator", () => {
  test("renders a task-first skill from the advertised MCP profiles", () => {
    const required = [
      "get_capabilities",
      "ensure_ready",
      "start_dev_session",
      "get_dev_session",
      "stop_dev_session",
      "inspect_app",
      "inspect_failures",
      "inspect_ui",
      "capture_screenshot",
    ];
    const output = renderAgentSkill({
      packageVersion: "0.6.0",
      tools: required.map((name, index) => ({
        name,
        _meta:
          index === 0
            ? { "dev.adbready/tool": { profiles: ["full", "debug", 3, null] } }
            : index === 1
              ? { "dev.adbready/tool": { profiles: ["full"] } }
              : index === 2
                ? { "dev.adbready/tool": null }
                : {},
      })),
    });

    expect(output).toContain("Generated by adb-ready 0.6.0");
    expect(output).toContain("- `debug`: 1 tools");
    expect(output).toContain("- `full`: 2 tools");
    expect(output).toContain("Do not replace them with generic shell or raw ADB commands");
  });

  test("refuses to generate a skill that references unavailable tools", () => {
    expect(() => renderAgentSkill({ packageVersion: "0.6.0", tools: [] })).toThrow(
      "Agent Skill references missing MCP tools",
    );
  });

  test("compacts primitive arrays only when the indented line stays within the formatter width", () => {
    const output = stringifyAgentContract({
      short: ["one", "two"],
      nested: {
        decision: [
          "allow",
          "allow-always",
          "allow-once",
          "allow-while-using",
          "deny",
          "deny-and-dont-ask-again",
        ],
      },
    });
    expect(output).toContain('"short": ["one", "two"]');
    expect(output).toContain('"decision": [\n');
    expect(Math.max(...output.split("\n").map((line) => line.length))).toBeLessThanOrEqual(100);
    expect(JSON.parse(output)).toEqual({
      short: ["one", "two"],
      nested: {
        decision: [
          "allow",
          "allow-always",
          "allow-once",
          "allow-while-using",
          "deny",
          "deny-and-dont-ask-again",
        ],
      },
    });
  });
});
